apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-adservice
spec:
  selector:
    matchLabels:
      app: eshop-adservice
  template:
    metadata:
      labels:
        app: eshop-adservice
    spec:
      replicas: 2
      containers:
        - name: eshop-adservice
          image: gcr.io/architect-certification-289902/11/eshop-adservice:1
          ports:
          - containerPort: 8095
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/eshop_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "eshop_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-adservice
spec:
  type: ClusterIP
  selector:
    app: eshop-adservice
  ports:
  - port: 8095