apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-cartservice1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-cartservice
  template:
    metadata:
      labels:
        app: eshop-cartservice
    spec:
      containers:
        - name: eshop-cartservice
          image: gcr.io/architect-certification-289902/11/eshop-cartservice:1
          ports:
          - containerPort: 8091
          env:
            - name: SPRING_REDIS_CLUSTER_NODES
              value: redis-redis-cluster.default.svc.cluster.local:6379
            - name: SPRING_REDIS_CLUSTER_MAX-REDIRECTS
              value: "3"
            - name: NATS_SPRING_SERVER
              value: "nats://nats-cluster.default.svc.cluster.local:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-cartservice
spec:
  type: ClusterIP
  selector:
    app: eshop-cartservice
  ports:
  - port: 8091
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: eshop-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eshop-frontend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50  